<?xml version="1.0" ?>
<robot name="xpider_set_legs_1" xmlns:xacro="http://ros.org/wiki/xacro">

  <joint name="base_link_to_step_up_1" type="revolute">
		<parent link="base_link" />
		<child link="step_up_1" />
    <origin xyz="${diameter_step_up} 0 ${base_link_to_step_up}" rpy="0 ${m_pi_6/2} 0"/>
    <limit effort="1000.0" lower="-0.1" upper="0.1" velocity="0.5"/>
    <axis xyz="0 1 0"/>
	</joint>

  <xacro:step_up num="1"/>

  <joint name="base_link_to_step_up_2" type="revolute">
		<parent link="base_link" />
		<child link="step_up_2" />
    <origin xyz="${diameter_step_up*cos_m_2_pi_3} ${diameter_step_up*sin_m_2_pi_3} ${base_link_to_step_up}" rpy="0 ${m_pi_6/2} ${m_2_pi_3}"/>
    <limit effort="1000.0" lower="-0.1" upper="0.1" velocity="0.5"/>
    <axis xyz="0 1 0"/>
	</joint>

  <xacro:step_up num="2"/>

  <joint name="base_link_to_step_up_3" type="revolute">
		<parent link="base_link" />
		<child link="step_up_3" />
    <origin xyz="${diameter_step_up*cos_m_4_pi_3} ${diameter_step_up*sin_m_4_pi_3} ${base_link_to_step_up}" rpy="0 ${m_pi_6/2} ${2*m_2_pi_3}"/>
    <limit effort="1000.0" lower="-0.1" upper="0.1" velocity="0.5"/>
    <axis xyz="0 1 0"/>
	</joint>

  <xacro:step_up num="3"/>


  <joint name="step_up_1_to_leg_1" type="fixed">
		<parent link="step_up_1" />
		<child link="leg_1" />
    <origin xyz="${diameter_step_up_to_leg} ${0} ${0.007}" rpy="0 ${-m_pi/16} 0"/>
	</joint>

  <xacro:leg num="1"/>

  <joint name="step_up_2_to_leg_2" type="fixed">
		<parent link="step_up_2" />
		<child link="leg_2" />
    <origin xyz="${diameter_step_up_to_leg} ${0} ${0.007}" rpy="0 ${-m_pi/16} 0"/>
	</joint>

  <xacro:leg num="2"/>

  <joint name="step_up_3_to_leg_3" type="fixed">
		<parent link="step_up_3" />
		<child link="leg_3" />
    <origin xyz="${diameter_step_up_to_leg} ${0} ${0.007}" rpy="0 ${-m_pi/16} 0"/>
	</joint>

  <xacro:leg num="3"/>
</robot>
