<?xml version="1.0" ?>
<robot name="xpider_step_bridge" xmlns:xacro="http://ros.org/wiki/xacro">
<xacro:include filename="$(find xpider_resources)/urdf/common_materials.xacro"/>
<xacro:include filename="$(find xpider_resources)/urdf/common_constants.xacro"/>

    <xacro:macro name="step_bridge" params="num">
    <link name="step_bridge_${num}">
    <visual>
      <origin xyz="0 0 -${height_step/2}" rpy="${m_pi_2} 0 0"/>
      <geometry>
        <mesh filename="package://xpider_descriptions/meshes/leg.stl" scale="${ratio_stl} ${ratio_stl} ${ratio_stl}"/>
        <xacro:material_xpider_yellow />
      </geometry>
      <xacro:material_xpider_grey />
    </visual>
    <collision>
      <origin xyz="0 0 -${height_step/2}" rpy="${m_pi_2} 0 0 "/>
      <geometry>
        <mesh filename="package://xpider_descriptions/meshes/leg.stl" scale="${ratio_stl} ${ratio_stl} ${ratio_stl}"/>
        <xacro:material_xpider_yellow />
      </geometry>
    </collision>
    </link>
   </xacro:macro>

</robot>
