<?xml version="1.0" ?>
<robot name="xpider" xmlns:xacro="http://ros.org/wiki/xacro">
<xacro:include filename="$(find xpider_resources)/urdf/common_materials.xacro"/>
<xacro:include filename="$(find xpider_resources)/urdf/common_constants.xacro"/>
<xacro:include filename="$(find xpider_descriptions)/models/step_bridge.xacro"/>
<xacro:include filename="$(find xpider_descriptions)/models/leg.xacro"/>
<xacro:include filename="$(find xpider_descriptions)/models/step_up.xacro"/>
<xacro:include filename="$(find xpider_descriptions)/models/xpider.gazebo" />
<!--<xacro:include filename="$(find xpider_descriptions)/models/leg_shield.xacro"/>-->

  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
  </joint>

  <xacro:include filename="$(find xpider_descriptions)/models/base_link.xacro"/>

  <joint name="base_joint" type="fixed">
		<parent link="base_link" />
		<child link="shield_top" />
		<origin xyz="0 0 ${height_base}" rpy="0 0 ${m_pi_3}" /> <!-- TOCHECK-->
	</joint>

  <xacro:include filename="$(find xpider_descriptions)/models/shield_top.xacro"/>

  <joint name="base_joint2" type="fixed">
		<parent link="base_link" />
		<child link="shield_bottom" />
		<origin xyz="0 0 ${height_base}" rpy="0 0 ${m_pi_3 + m_pi_6}" />
	</joint>

  <xacro:include filename="$(find xpider_descriptions)/models/shield_bottom.xacro"/>

  <joint name="base_joint3" type="fixed">
		<parent link="base_link" />
		<child link="step" />
		<origin xyz="0 0 ${base_link_to_step_height + height_step/2}" rpy="0 0 ${m_pi_2 + m_pi_6}" />
	</joint>

   <xacro:include filename="$(find xpider_descriptions)/models/step.xacro"/>

  <joint name="base_joint4" type="fixed">
		<parent link="base_link" />
		<child link="step_base" />
		<origin xyz="0 0 ${height_base}" rpy="0 0 ${m_pi_3 + m_pi_6}" />
	</joint>

  <xacro:include filename="$(find xpider_descriptions)/models/step_base.xacro"/>

  <!--  Legs -->
  <joint name="base_link_to_leg_1" type="fixed">
		<parent link="base_link" />
		<child link="leg_1" />
    <origin xyz="${diameter_step} 0 ${base_link_to_step_height + height_leg}" rpy="0 0 0"/>
	</joint>

  <xacro:leg num="1"/>

  <joint name="base_link_to_leg_2" type="fixed">
		<parent link="base_link" />
		<child link="leg_2" />
    <origin xyz="${diameter_step*cos_m_2_pi_3} ${diameter_step*sin_m_2_pi_3} ${base_link_to_step_height + height_step/2}" rpy="0 0 ${m_2_pi_3}"/>
	</joint>

  <xacro:leg num="2"/>

  <joint name="base_link_to_leg_3" type="fixed">
		<parent link="base_link" />
		<child link="leg_3" />
    <origin xyz="${diameter_step*cos_m_4_pi_3} ${diameter_step*sin_m_4_pi_3} ${base_link_to_step_height + height_step/2}" rpy="0 0 ${2*m_2_pi_3}"/>
	</joint>

  <xacro:leg num="3"/>

  <joint name="base_link_to_step_up_1" type="fixed">
		<parent link="base_link" />
		<child link="step_up_1" />
    <origin xyz="${diameter_step_up} 0 ${base_link_to_step_up}" rpy="0 ${m_pi_6} 0"/>
	</joint>

  <xacro:step_up num="1"/>

  <joint name="base_link_to_step_up_2" type="fixed">
		<parent link="base_link" />
		<child link="step_up_2" />
    <origin xyz="${diameter_step_up*cos_m_2_pi_3} ${diameter_step_up*sin_m_2_pi_3} ${base_link_to_step_up}" rpy="0 ${m_pi_6} ${m_2_pi_3}"/>
	</joint>

  <xacro:step_up num="2"/>

  <joint name="base_link_to_step_up_3" type="fixed">
		<parent link="base_link" />
		<child link="step_up_3" />
    <origin xyz="${diameter_step_up*cos_m_4_pi_3} ${diameter_step_up*sin_m_4_pi_3} ${base_link_to_step_up}" rpy="0 ${m_pi_6} ${2*m_2_pi_3}"/>
	</joint>

  <xacro:step_up num="3"/>


<!--  <joint name="base_link_to_leg_4" type="fixed">
		<parent link="base_link" />
		<child link="leg_4" />
    <origin xyz="0 0 0" rpy="0 ${m_pi} 0"/>
	</joint>

        <link name="leg_4">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://xpider_descriptions/meshes/leg.stl" scale="${ratio_stl} ${ratio_stl} ${ratio_stl}"/>
          <xacro:color_xpider_white />
        </geometry>
        </visual>
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <mesh filename="package://xpider_descriptions/meshes/leg.stl" scale="${ratio_stl} ${ratio_stl} ${ratio_stl}"/>
            <xacro:color_xpider_white />
          </geometry>
        </collision>
      </link>-->

<!--   <joint name="base_link_to_leg_shield_3" type="fixed">
		<parent link="leg_1" />
		<child link="leg_shield_1" />
    <origin xyz="0 0 0" rpy="-${m_pi_2} 0 0"/>
	</joint>

  <xacro:leg_shield num="1"/>-->

</robot>
