<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Pi, the ratio of a circle's circumference to its diameter -->
  <xacro:property name="m_pi" value="3.1415926535" />
  <!-- Pi divided by two -->
  <xacro:property name="m_pi_2" value="1.570796327" />
  <!-- 3Pi divided by two -->
  <xacro:property name="m_3_pi_2" value="2.35619449" />
  <!-- 3Pi divided by two -->
  <xacro:property name="m_2_pi_3" value="2.09439510239" />
  <!-- Pi divided by four -->
  <xacro:property name="m_pi_4" value="0.785398163" />
  <!-- Pi divided by three -->
  <xacro:property name="m_pi_3" value="1.0471975512" />
  <!-- Pi divided by six -->
  <xacro:property name="m_pi_6" value="0.52359877559" />

  <xacro:property name="cos_m_pi" value="-1" />
  <xacro:property name="sin_m_pi" value="0" />
  <xacro:property name="cos_m_pi_2" value="0" />
  <xacro:property name="sin_m_pi_2" value="1" />
  <xacro:property name="cos_m_pi_6" value="0.5" />
  <xacro:property name="sin_m_pi_6" value="0.86602540378" />
  <xacro:property name="cos_m_pi_3" value="0.5" />
  <xacro:property name="sin_m_pi_3" value="0.86602540378" />
  <xacro:property name="cos_m_2_pi_3" value="-0.5" />
  <xacro:property name="sin_m_2_pi_3" value="0.86602540378" />
  <xacro:property name="cos_m_4_pi_3" value="-0.5" />
  <xacro:property name="sin_m_4_pi_3" value="-0.86602540378" />
  <xacro:property name="cos_m_5_pi_3" value="0.5" />
  <xacro:property name="sin_m_5_pi_3" value="-0.86602540378" />
  <xacro:property name="cos_m_5_pi_6" value="-0.86602540378" />
  <xacro:property name="sin_m_5_pi_6" value="0.5" />

  <xacro:property name="ratio_stl" value="0.01006046568"/>

  <xacro:property name="height_base" value="${48.705498889*ratio_stl}"/>
  <xacro:property name="height_step" value="0.04"/>
  <xacro:property name="height_leg" value="${height_step/2 + 0.007}"/>
  <xacro:property name="base_link_to_step_height" value="${height_base-0.28}"/>
  <xacro:property name="base_link_to_step_up" value="${height_base - 0.05}"/>
  <xacro:property name="diameter_step" value="${53.7748467325*ratio_stl}" />
  <xacro:property name="diameter_step_up" value="${26*ratio_stl}" />
  <xacro:property name="diameter_step_connect" value="${5.5*ratio_stl}" />
  <xacro:property name="height_step_connect_to_step_b" value="${3.99583888844*ratio_stl}" />
  <xacro:property name="diameter_step_connect_to_step_b" value="${4.17475704763*ratio_stl}" />
  <xacro:property name="height_base_link_to_step_c" value="${base_link_to_step_height-0.99398977324*ratio_stl}"/>
  <xacro:property name="diameter_step_c" value="${26*ratio_stl}" />



</robot>
